# Generated by Django 5.2.1 on 2025-06-07 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_privatechatroom_privatemessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatemessage',
            name='room',
        ),
        migrations.RemoveField(
            model_name='privatemessage',
            name='user',
        ),
        migrations.DeleteModel(
            name='PrivateChatRoom',
        ),
        migrations.DeleteModel(
            name='PrivateMessage',
        ),
    ]
